subo ejerciccios de tarea de 3
sergio-ceballos-intelex/tareas-modulo-3-grupo-9 pull request #40
Opened 2024-06-27 15:14 UTC by RSuarezwilli

se realiza ejercicios de ja. script números del 1 al 50 por consola

2024-07-01 16:54 UTC, sergio-ceballos-intelex requested changes
falto la captura de pantalla con el comando git que hay ejecutar (revisar la descripcion de la tarea)

2024-07-03 03:22 UTC, RSuarezwilli commented
> falto la captura de pantalla con el comando git que hay ejecutar (revisar la descripcion de la tarea

![image](https://github.com/sergio-ceballos-intelex/tareas-modulo-3-grupo-9/assets/124012658/de897a47-d11c-41ad-9eaa-906ca76fc427)

2024-07-03 03:25 UTC, RSuarezwilli commented
![image](https://github.com/sergio-ceballos-intelex/tareas-modulo-3-grupo-9/assets/124012658/f1dab2ab-fc04-4f5f-8bf6-45fc7abae8fd)

2024-07-03 20:56 UTC, sergio-ceballos-intelex approved these changes

2024-07-03 20:56 UTC, merged